# WARNING - Generated by {fusen} from dev/flat_full.Rmd: do not edit by hand


test_that("get_color_hex_code works properly and show error if needed", {
  set.seed(123)
  myc <- tibble(color_names = sample(colors(),5), 
                     hex_code = colorRampPalette(color_names)(length(color_names)))
  
  expect_true(get_color_hex_code('mediumorchid1', base_colors = myc) == '#E066FF')
  expect_warning(get_color_hex_code("fuchsia", base_colors = myc), 'fuchsia not part of base_colors')
  expect_error(get_color_hex_code("mediumorchid1", base_colors = asdf), "object 'asdf' not found")
})

