# WARNING - Generated by {fusen} from dev/flat_full.Rmd: do not edit by hand


  set.seed(123)
  myc <- tibble(color_names = sample(colors(),5), 
                     hex_code = colorRampPalette(color_names)(length(color_names)))
  
  base_cols <- generate_colors_to_interpolate(myc, 2)
  
  # interpolate first element of base_cols
  myc_interpolated <- color_palette(
    colors_to_interpolate = 'pal1',
    base_colors = base_cols
  )
 
  testthat::expect_true(
    class(myc_interpolated) == 'function'
  )
  
