# WARNING - Generated by {fusen} from dev/flat_full.Rmd: do not edit by hand

#' Create a function that allows to interpolate and acces colors. 
#'
#' @param colors_to_interpolate Name of the colors to interpolate. It is the name of a list element as generated by the function [generate_colors_to_interpolate()]. 
#' @param base_colors A list of colors to interplotate. Output from [generate_colors_to_interpolate()].
#' @param reverse Boolean indicating whether or not to reverse the order of the colors.
#' @param ... Other arguments to [grDevices::colorRampPalette]
#'
#' @return
#' A function interpolating colors.
#' 
#' @export
#'
#' @examples
#' datafile <- system.file("mycolors.csv", 
#'                         package = "stadlColorPaletteR")
#' mycolors <- readr::read_csv(datafile)
#'
#' # combinations with 2 colors
#' base_cols <- generate_colors_to_interpolate(mycolors, 2)
#'
#' # interpolate first element of base_cols
#' mycolors_interpolated <- color_palette(
#'   colors_to_interpolate = 'pal1',
#'   base_colors = base_cols
#' )
#'
color_palette <- function(colors_to_interpolate, 
                      base_colors, 
                      reverse = FALSE, ...) {
  pal <- base_colors[[colors_to_interpolate]]
  if (reverse) pal <- rev(pal)
  colorRampPalette(pal, ...)
}
