# WARNING - Generated by {fusen} from dev/flat_full.Rmd: do not edit by hand

#' Get hex code of colors
#'
#' @param ... Names of colors as character 
#' @param colors A tibble with color_names and hex_codes as columns
#'
#' @return
#' Hex code of colors specified
#' 
#' @export TRUE
#'
#' @examples
#' my_median(1:12)
#'
#' # Example with your dataset in "inst/"
#' datafile <- system.file("nyc_squirrels_sample.csv", package = "stadlColorPaletteR")
#' nyc_squirrels <- read.csv(datafile, encoding = "UTF-8")
#' # Apply my function
#' my_median(nyc_squirrels[,"hectare_squirrel_number"])
get_color_hex_code <- function(..., colors = mycolors) {
  cols <- c(...)
  if (is.null(cols))
    return (colors %>% pull(hex_code))
  colors %>% dplyr::filter(color_names %in% cols) %>% pull(hex_code)
}
