# WARNING - Generated by {fusen} from dev/flat_full.Rmd: do not edit by hand

#' Generate all possible combination of n colors from the total number N of colors provided. Will be used later for interpolation. 
#'
#' @param colors A tibble with color_names and hex_codes as columns. 
#' @param n An integer between 1 and number of colors provided.
#'
#' @return
#' A list of length C(N,n), each element containing n colors, where C(N,n) denotes the number of n-combination from a set of N elements. 
#' 
#' @export
#'
#' @examples
#' datafile <- system.file("mycolors.csv", 
#'                         package = "stadlColorPaletteR")
#' mycolors <- readr::read_csv(datafile)
#'
#' # combinations with 2 colors
#' generate_colors_to_interpolate(mycolors, 2)
#'
#' #combinations with all colors
#' generate_colors_to_interpolate(mycolors, nrow(mycolors))
#'
generate_colors_to_interpolate <- function(colors, n){
  if(n<1) {
    stop("n must be greater than 1")
  }
  pal <- combn(get_color_hex_code(base_colors = colors),n)
  colnames(pal) <- paste('pal',1:ncol(pal), sep = '')
  as.list(
    as.data.frame(pal)
  )
}

#' Get hex code of colors
#'
#' @param ... Names of colors as character 
#' @param base_colors A tibble with color_names and hex_codes as columns
#'
#' @return
#' Hex code of colors specified
#' 
#' @export
#'
#' @examples
#' datafile <- system.file("mycolors.csv", 
#'                         package = "stadlColorPaletteR")
#' mycolors <- readr::read_csv(datafile)
#' get_color_hex_code('palevioletred2', base_colors = mycolors)
#'
get_color_hex_code <- function(..., base_colors) {

  cols <- c(...)
  if (is.null(cols))
    return (base_colors %>% dplyr::pull(hex_code))
  if (!all(cols%in%base_colors$color_names)){
    not <- cols[!cols%in%base_colors$color_names]
    warning(paste(not, collapse=', '), 
            ' not part of base_colors!')
  }
    
  base_colors %>% 
    dplyr::filter(
      color_names %in% cols) %>% 
    dplyr::pull(hex_code)
}
