# WARNING - Generated by {fusen} from dev/flat_full.Rmd: do not edit by hand

#' Get hex code of colors
#'
#' @param ... Names of colors as character 
#' @param base_colors A tibble with color_names and hex_codes as columns
#'
#' @return
#' Hex code of colors specified
#' 
#' @export
#'
#' @examples
#' datafile <- system.file("mycolors.csv", 
#'                         package = "stadlColorPaletteR")
#' mycolors <- readr::read_csv(datafile)
#' get_color_hex_code('palevioletred2')
#'
get_color_hex_code <- function(..., base_colors = mycolors) {

  cols <- c(...)
  if (is.null(cols))
    return (base_colors %>% dplyr::pull(hex_code))
  if (!all(cols%in%base_colors$color_names)){
    not <- cols[!cols%in%base_colors$color_names]
    warning(paste(not, collapse=', '), 
            ' not part of base_colors!')
  }
    
  base_colors %>% 
    dplyr::filter(
      color_names %in% cols) %>% 
    dplyr::pull(hex_code)
}
