# WARNING - Generated by {fusen} from dev/flat_full.Rmd: do not edit by hand

#' Create function for color scales 
#'
#' @param colors_to_interpolate Name of the colors to interpolate. It is the name of a list element as generated by the function [generate_colors_to_interpolate()]. 
#' @param base_colors A list of colors to interplotate. Output from [generate_colors_to_interpolate()].
#' @param reverse Boolean indicating whether or not to reverse the order of the colors.
#' @param discrete Boolean indicating whetehr or not to use discrete scale
#' @param ... Other arguments to [grDevices::colorRampPalette]
#'
#' @return
#' A function for scales to use in ggplot.
#' 
#' @export
#'
#' @examples
#' require(ggplot2)
#' datafile <- system.file("mycolors.csv", 
#'                         package = "stadlColorPaletteR")
#' mycolors <- readr::read_csv(datafile)
#' ggplot(iris, 
#'        aes(Sepal.Width, Sepal.Length, color = Species)) +
#'   geom_point(size = 2, alpha = 1) +
#'   scale_color_stadl('pal1', generate_colors_to_interpolate(mycolors,3)) +
#'   ggtitle("stadl")+theme_minimal()
#'
scale_color_stadl <- function(colors_to_interpolate = "pal1", base_colors_set = stadl2,
                              discrete = TRUE, reverse = FALSE, subset = as.vector(NULL), ...) {
  pal <- color_palette(colors_to_interpolate = colors_to_interpolate, 
                       reverse = reverse, base_colors_set = base_colors_set, subset = subset)

  if (discrete) {
    discrete_scale("colour", paste0("stadl_", colors_to_interpolate), palette = pal, ...)
  } else {
    scale_color_gradientn(colours = pal(256), ...)
  }
}


#' Create function for filling scales. 
#'
#' @param colors_to_interpolate Name of the colors to interpolate. It is the name of a list element as generated by the function [generate_colors_to_interpolate()]. 
#' @param base_colors A list of colors to interplotate. Output from [generate_colors_to_interpolate()].
#' @param reverse Boolean indicating whether or not to reverse the order of the colors.
#' @param ... Other arguments to [grDevices::colorRampPalette]
#'
#' @return
#' A function interpolating colors.
#' 
#' @export
#'
scale_fill_stadl <- function(colors_to_interpolate = "pal1", base_colors_set = stadl2,
                              discrete = TRUE, reverse = FALSE, subset = as.vector(NULL), ...) {
  pal <- color_palette(colors_to_interpolate = colors_to_interpolate, 
                       reverse = reverse, base_colors_set = base_colors_set, subset = subset)

  if (discrete) {
    discrete_scale("colour", paste0("stadl_", colors_to_interpolate), palette = pal, ...)
  } else {
    scale_color_gradientn(colours = pal(256), ...)
  }
}

